// <auto-generated />
using API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(PizzaCalculatorDbContext))]
    partial class PizzaCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Entidades.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ing_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marca")
                        .HasColumnType("longtext")
                        .HasColumnName("ing_marca");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("ing_nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("ing_preco");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ing_status");

                    b.HasKey("Id");

                    b.ToTable("tbc_ingrediente");
                });

            modelBuilder.Entity("API.Domain.Entidades.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModoPreparo")
                        .HasColumnType("longtext")
                        .HasColumnName("rec_modo_preparo");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("rec_nome");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("rec_status");

                    b.HasKey("Id");

                    b.ToTable("tbc_receita");
                });

            modelBuilder.Entity("API.Domain.Entidades.ReceitaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int")
                        .HasColumnName("ing_id");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("percentual");

                    b.Property<decimal>("PesoG")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("rec_item_peso_g");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("tbc_receita_item");
                });

            modelBuilder.Entity("API.Domain.Entidades.ReceitaItem", b =>
                {
                    b.HasOne("API.Domain.Entidades.Ingrediente", "Ingrediente")
                        .WithMany("ReceitaItens")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Domain.Entidades.Receita", "Receita")
                        .WithMany("Itens")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("API.Domain.Entidades.Ingrediente", b =>
                {
                    b.Navigation("ReceitaItens");
                });

            modelBuilder.Entity("API.Domain.Entidades.Receita", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
